using System;
using System.Collections.Generic;

namespace StockFilterToolsV1.Models
{
    public class IncomeStatementModel
    {
        public int page { get; set; }
        public int pageSize { get; set; }
        public int totalCount { get; set; }
        public List<Item> items { get; set; }
        public object packageId { get; set; }
        public string status { get; set; }
        public object errors { get; set; }


        public class Item
        {
            public List<Quarterly> quarterly { get; set; }
            public List<Yearly> yearly { get; set; }
            public List<SixMonth> sixMonths { get; set; }
            public List<NineMonth> nineMonths { get; set; }
        }

        public class NineMonth
        {
            public string organCode { get; set; }
            public int yearReport { get; set; }
            public int quarterReport { get; set; }
            public double? isb27 { get; set; }
            public double? isb30 { get; set; }
            public double? isb38 { get; set; }
            public double? isb41 { get; set; }
            public double isa20 { get; set; }
            public double isa1 { get; set; }
            public double isa11 { get; set; }
            public object rtq29 { get; set; }
            public double? isb25 { get; set; }
            public double? isb26 { get; set; }
            public double? isb28 { get; set; }
            public double? isb29 { get; set; }
            public double? isb31 { get; set; }
            public double? isb32 { get; set; }
            public double? isb33 { get; set; }
            public double? isb34 { get; set; }
            public double? isb35 { get; set; }
            public double? isb36 { get; set; }
            public double? isb37 { get; set; }
            public double? isb39 { get; set; }
            public double? isb40 { get; set; }
            public double isa16 { get; set; }
            public double isa17 { get; set; }
            public double isa18 { get; set; }
            public double isa19 { get; set; }
            public double isa21 { get; set; }
            public double isa22 { get; set; }
            public double isa23 { get; set; }
            public double isa2 { get; set; }
            public double isa3 { get; set; }
            public double isa4 { get; set; }
            public double isa5 { get; set; }
            public double isa6 { get; set; }
            public double isa7 { get; set; }
            public double isa8 { get; set; }
            public double isa15 { get; set; }
            public double isa9 { get; set; }
            public double isa10 { get; set; }
            public double isa12 { get; set; }
            public double isa13 { get; set; }
            public double isa14 { get; set; }
            public double isa24 { get; set; }
            public double isa102 { get; set; }
            public double? isi103 { get; set; }
            public double? isi104 { get; set; }
            public double? isi51 { get; set; }
            public double? isi52 { get; set; }
            public double? isi53 { get; set; }
            public double? isi54 { get; set; }
            public double? isi55 { get; set; }
            public double? isi56 { get; set; }
            public double? isi57 { get; set; }
            public double? isi105 { get; set; }
            public double? isi58 { get; set; }
            public double? isi59 { get; set; }
            public double? isi106 { get; set; }
            public double? isi60 { get; set; }
            public double? isi61 { get; set; }
            public double? isi62 { get; set; }
            public double? isi63 { get; set; }
            public double? isi64 { get; set; }
            public double? isi65 { get; set; }
            public double? isi66 { get; set; }
            public double? isi67 { get; set; }
            public double? isi68 { get; set; }
            public double? isi69 { get; set; }
            public double? isi70 { get; set; }
            public double? isi176 { get; set; }
            public double? isi175 { get; set; }
            public double? isi107 { get; set; }
            public double? isi71 { get; set; }
            public double? isi108 { get; set; }
            public double? isi109 { get; set; }
            public double? isi110 { get; set; }
            public double? isi73 { get; set; }
            public double? isi111 { get; set; }
            public double? isi72 { get; set; }
            public double? isi74 { get; set; }
            public double? isi75 { get; set; }
            public double? isi76 { get; set; }
            public double? isi77 { get; set; }
            public double? isi78 { get; set; }
            public double? isi79 { get; set; }
            public double? isi80 { get; set; }
            public double? isi81 { get; set; }
            public double? isi82 { get; set; }
            public double? isi83 { get; set; }
            public double? isi84 { get; set; }
            public double? isi85 { get; set; }
            public double? isi86 { get; set; }
            public double? isi87 { get; set; }
            public double? isi90 { get; set; }
            public double? isi88 { get; set; }
            public double? isi89 { get; set; }
            public double? isi177 { get; set; }
            public double? isi178 { get; set; }
            public double? isi179 { get; set; }
            public double? isi180 { get; set; }
            public double? isi100 { get; set; }
            public double? isi93 { get; set; }
            public double? isi91 { get; set; }
            public double? isi92 { get; set; }
            public double? isi97 { get; set; }
            public double? isi112 { get; set; }
            public double? isi113 { get; set; }
            public double? isi114 { get; set; }
            public double? isi94 { get; set; }
            public double? isi95 { get; set; }
            public double? isi96 { get; set; }
            public double? isi98 { get; set; }
            public double? isi99 { get; set; }
            public double? isi101 { get; set; }
            public double? iss115 { get; set; }
            public double? iss116 { get; set; }
            public double? iss117 { get; set; }
            public double? iss118 { get; set; }
            public double? iss119 { get; set; }
            public double? iss120 { get; set; }
            public double? iss121 { get; set; }
            public double? iss122 { get; set; }
            public double? iss42 { get; set; }
            public double? iss44 { get; set; }
            public double? iss45 { get; set; }
            public double? iss46 { get; set; }
            public double? iss48 { get; set; }
            public double? iss47 { get; set; }
            public double? iss43 { get; set; }
            public double? iss49 { get; set; }
            public double? iss123 { get; set; }
            public double? iss50 { get; set; }
            public double? iss124 { get; set; }
            public double? iss125 { get; set; }
            public double? iss126 { get; set; }
            public double? iss127 { get; set; }
            public double? iss128 { get; set; }
            public double? iss129 { get; set; }
            public double? iss130 { get; set; }
            public double? iss168 { get; set; }
            public double? iss131 { get; set; }
            public double? iss132 { get; set; }
            public double? iss133 { get; set; }
            public double? iss134 { get; set; }
            public double? iss135 { get; set; }
            public double? iss136 { get; set; }
            public double? iss137 { get; set; }
            public double? iss138 { get; set; }
            public double? iss139 { get; set; }
            public double? iss141 { get; set; }
            public double? iss142 { get; set; }
            public double? iss143 { get; set; }
            public double? iss144 { get; set; }
            public double? iss145 { get; set; }
            public double? iss146 { get; set; }
            public double? iss147 { get; set; }
            public double? iss148 { get; set; }
            public double? iss149 { get; set; }
            public double? iss150 { get; set; }
            public double? iss151 { get; set; }
            public double? iss152 { get; set; }
            public double? iss153 { get; set; }
            public double? iss154 { get; set; }
            public double? iss155 { get; set; }
            public double? iss164 { get; set; }
            public double? iss156 { get; set; }
            public double? iss157 { get; set; }
            public double? iss158 { get; set; }
            public double? iss159 { get; set; }
            public double? iss160 { get; set; }
            public double? iss161 { get; set; }
            public double? iss162 { get; set; }
            public double? iss163 { get; set; }
            public double? iss165 { get; set; }
            public double? iss166 { get; set; }
            public double? iss167 { get; set; }
            public double cfa2 { get; set; }
            public double ebit { get; set; }
            public double ebitDa { get; set; }
        }

        public class Quarterly
        {
            public string organCode { get; set; }
            public int yearReport { get; set; }
            public int quarterReport { get; set; }
            public double? isb27 { get; set; }
            public double? isb30 { get; set; }
            public double? isb38 { get; set; }
            public double? isb41 { get; set; }
            public double isa20 { get; set; }
            public double isa1 { get; set; }
            public double isa11 { get; set; }
            public double? rtq29 { get; set; }
            public double? isb25 { get; set; }
            public double? isb26 { get; set; }
            public double? isb28 { get; set; }
            public double? isb29 { get; set; }
            public double? isb31 { get; set; }
            public double? isb32 { get; set; }
            public double? isb33 { get; set; }
            public double? isb34 { get; set; }
            public double? isb35 { get; set; }
            public double? isb36 { get; set; }
            public double? isb37 { get; set; }
            public double? isb39 { get; set; }
            public double? isb40 { get; set; }
            public double isa16 { get; set; }
            public double isa17 { get; set; }
            public double isa18 { get; set; }
            public double isa19 { get; set; }
            public double isa21 { get; set; }
            public double isa22 { get; set; }
            public double isa23 { get; set; }
            public double isa2 { get; set; }
            public double isa3 { get; set; }
            public double isa4 { get; set; }
            public double isa5 { get; set; }
            public double isa6 { get; set; }
            public double isa7 { get; set; }
            public double isa8 { get; set; }
            public double isa15 { get; set; }
            public double isa9 { get; set; }
            public double isa10 { get; set; }
            public double isa12 { get; set; }
            public double isa13 { get; set; }
            public double isa14 { get; set; }
            public double isa24 { get; set; }
            public double isa102 { get; set; }
            public double? isi103 { get; set; }
            public double? isi104 { get; set; }
            public double? isi51 { get; set; }
            public double? isi52 { get; set; }
            public double? isi53 { get; set; }
            public double? isi54 { get; set; }
            public double? isi55 { get; set; }
            public double? isi56 { get; set; }
            public double? isi57 { get; set; }
            public double? isi105 { get; set; }
            public double? isi58 { get; set; }
            public double? isi59 { get; set; }
            public double? isi106 { get; set; }
            public double? isi60 { get; set; }
            public double? isi61 { get; set; }
            public double? isi62 { get; set; }
            public double? isi63 { get; set; }
            public double? isi64 { get; set; }
            public double? isi65 { get; set; }
            public double? isi66 { get; set; }
            public double? isi67 { get; set; }
            public double? isi68 { get; set; }
            public double? isi69 { get; set; }
            public double? isi70 { get; set; }
            public double? isi176 { get; set; }
            public double? isi175 { get; set; }
            public double? isi107 { get; set; }
            public double? isi71 { get; set; }
            public double? isi108 { get; set; }
            public double? isi109 { get; set; }
            public double? isi110 { get; set; }
            public double? isi73 { get; set; }
            public double? isi111 { get; set; }
            public double? isi72 { get; set; }
            public double? isi74 { get; set; }
            public double? isi75 { get; set; }
            public double? isi76 { get; set; }
            public double? isi77 { get; set; }
            public double? isi78 { get; set; }
            public double? isi79 { get; set; }
            public double? isi80 { get; set; }
            public double? isi81 { get; set; }
            public double? isi82 { get; set; }
            public double? isi83 { get; set; }
            public double? isi84 { get; set; }
            public double? isi85 { get; set; }
            public double? isi86 { get; set; }
            public double? isi87 { get; set; }
            public double? isi90 { get; set; }
            public double? isi88 { get; set; }
            public double? isi89 { get; set; }
            public double? isi177 { get; set; }
            public double? isi178 { get; set; }
            public double? isi179 { get; set; }
            public double? isi180 { get; set; }
            public double? isi100 { get; set; }
            public double? isi93 { get; set; }
            public double? isi91 { get; set; }
            public double? isi92 { get; set; }
            public double? isi97 { get; set; }
            public double? isi112 { get; set; }
            public double? isi113 { get; set; }
            public double? isi114 { get; set; }
            public double? isi94 { get; set; }
            public double? isi95 { get; set; }
            public double? isi96 { get; set; }
            public double? isi98 { get; set; }
            public double? isi99 { get; set; }
            public double? isi101 { get; set; }
            public double? iss115 { get; set; }
            public double? iss116 { get; set; }
            public double? iss117 { get; set; }
            public double? iss118 { get; set; }
            public double? iss119 { get; set; }
            public double? iss120 { get; set; }
            public double? iss121 { get; set; }
            public double? iss122 { get; set; }
            public double? iss42 { get; set; }
            public double? iss44 { get; set; }
            public double? iss45 { get; set; }
            public double? iss46 { get; set; }
            public double? iss48 { get; set; }
            public double? iss47 { get; set; }
            public double? iss43 { get; set; }
            public double? iss49 { get; set; }
            public double? iss123 { get; set; }
            public double? iss50 { get; set; }
            public double? iss124 { get; set; }
            public double? iss125 { get; set; }
            public double? iss126 { get; set; }
            public double? iss127 { get; set; }
            public double? iss128 { get; set; }
            public double? iss129 { get; set; }
            public double? iss130 { get; set; }
            public double? iss168 { get; set; }
            public double? iss131 { get; set; }
            public double? iss132 { get; set; }
            public double? iss133 { get; set; }
            public double? iss134 { get; set; }
            public double? iss135 { get; set; }
            public double? iss136 { get; set; }
            public double? iss137 { get; set; }
            public double? iss138 { get; set; }
            public double? iss139 { get; set; }
            public double? iss141 { get; set; }
            public double? iss142 { get; set; }
            public double? iss143 { get; set; }
            public double? iss144 { get; set; }
            public double? iss145 { get; set; }
            public double? iss146 { get; set; }
            public double? iss147 { get; set; }
            public double? iss148 { get; set; }
            public double? iss149 { get; set; }
            public double? iss150 { get; set; }
            public double? iss151 { get; set; }
            public double? iss152 { get; set; }
            public double? iss153 { get; set; }
            public double? iss154 { get; set; }
            public double? iss155 { get; set; }
            public double? iss164 { get; set; }
            public double? iss156 { get; set; }
            public double? iss157 { get; set; }
            public double? iss158 { get; set; }
            public double? iss159 { get; set; }
            public double? iss160 { get; set; }
            public double? iss161 { get; set; }
            public double? iss162 { get; set; }
            public double? iss163 { get; set; }
            public double? iss165 { get; set; }
            public double? iss166 { get; set; }
            public double? iss167 { get; set; }
            public double cfa2 { get; set; }
            public double ebit { get; set; }
            public double ebitDa { get; set; }
        }

        public class SixMonth
        {
            public string organCode { get; set; }
            public int yearReport { get; set; }
            public int quarterReport { get; set; }
            public double? isb27 { get; set; }
            public double? isb30 { get; set; }
            public double? isb38 { get; set; }
            public double? isb41 { get; set; }
            public double isa20 { get; set; }
            public double isa1 { get; set; }
            public double isa11 { get; set; }
            public object rtq29 { get; set; }
            public double? isb25 { get; set; }
            public double? isb26 { get; set; }
            public double? isb28 { get; set; }
            public double? isb29 { get; set; }
            public double? isb31 { get; set; }
            public double? isb32 { get; set; }
            public double? isb33 { get; set; }
            public double? isb34 { get; set; }
            public double? isb35 { get; set; }
            public double? isb36 { get; set; }
            public double? isb37 { get; set; }
            public double? isb39 { get; set; }
            public double? isb40 { get; set; }
            public double isa16 { get; set; }
            public double isa17 { get; set; }
            public double isa18 { get; set; }
            public double isa19 { get; set; }
            public double isa21 { get; set; }
            public double isa22 { get; set; }
            public double isa23 { get; set; }
            public double isa2 { get; set; }
            public double isa3 { get; set; }
            public double isa4 { get; set; }
            public double isa5 { get; set; }
            public double isa6 { get; set; }
            public double isa7 { get; set; }
            public double isa8 { get; set; }
            public double isa15 { get; set; }
            public double isa9 { get; set; }
            public double isa10 { get; set; }
            public double isa12 { get; set; }
            public double isa13 { get; set; }
            public double isa14 { get; set; }
            public double isa24 { get; set; }
            public double isa102 { get; set; }
            public double? isi103 { get; set; }
            public double? isi104 { get; set; }
            public double? isi51 { get; set; }
            public double? isi52 { get; set; }
            public double? isi53 { get; set; }
            public double? isi54 { get; set; }
            public double? isi55 { get; set; }
            public double? isi56 { get; set; }
            public double? isi57 { get; set; }
            public double? isi105 { get; set; }
            public double? isi58 { get; set; }
            public double? isi59 { get; set; }
            public double? isi106 { get; set; }
            public double? isi60 { get; set; }
            public double? isi61 { get; set; }
            public double? isi62 { get; set; }
            public double? isi63 { get; set; }
            public double? isi64 { get; set; }
            public double? isi65 { get; set; }
            public double? isi66 { get; set; }
            public double? isi67 { get; set; }
            public double? isi68 { get; set; }
            public double? isi69 { get; set; }
            public double? isi70 { get; set; }
            public double? isi176 { get; set; }
            public double? isi175 { get; set; }
            public double? isi107 { get; set; }
            public double? isi71 { get; set; }
            public double? isi108 { get; set; }
            public double? isi109 { get; set; }
            public double? isi110 { get; set; }
            public double? isi73 { get; set; }
            public double? isi111 { get; set; }
            public double? isi72 { get; set; }
            public double? isi74 { get; set; }
            public double? isi75 { get; set; }
            public double? isi76 { get; set; }
            public double? isi77 { get; set; }
            public double? isi78 { get; set; }
            public double? isi79 { get; set; }
            public double? isi80 { get; set; }
            public double? isi81 { get; set; }
            public double? isi82 { get; set; }
            public double? isi83 { get; set; }
            public double? isi84 { get; set; }
            public double? isi85 { get; set; }
            public double? isi86 { get; set; }
            public double? isi87 { get; set; }
            public double? isi90 { get; set; }
            public double? isi88 { get; set; }
            public double? isi89 { get; set; }
            public double? isi177 { get; set; }
            public double? isi178 { get; set; }
            public double? isi179 { get; set; }
            public double? isi180 { get; set; }
            public double? isi100 { get; set; }
            public double? isi93 { get; set; }
            public double? isi91 { get; set; }
            public double? isi92 { get; set; }
            public double? isi97 { get; set; }
            public double? isi112 { get; set; }
            public double? isi113 { get; set; }
            public double? isi114 { get; set; }
            public double? isi94 { get; set; }
            public double? isi95 { get; set; }
            public double? isi96 { get; set; }
            public double? isi98 { get; set; }
            public double? isi99 { get; set; }
            public double? isi101 { get; set; }
            public double? iss115 { get; set; }
            public double? iss116 { get; set; }
            public double? iss117 { get; set; }
            public double? iss118 { get; set; }
            public double? iss119 { get; set; }
            public double? iss120 { get; set; }
            public double? iss121 { get; set; }
            public double? iss122 { get; set; }
            public double? iss42 { get; set; }
            public double? iss44 { get; set; }
            public double? iss45 { get; set; }
            public double? iss46 { get; set; }
            public double? iss48 { get; set; }
            public double? iss47 { get; set; }
            public double? iss43 { get; set; }
            public double? iss49 { get; set; }
            public double? iss123 { get; set; }
            public double? iss50 { get; set; }
            public double? iss124 { get; set; }
            public double? iss125 { get; set; }
            public double? iss126 { get; set; }
            public double? iss127 { get; set; }
            public double? iss128 { get; set; }
            public double? iss129 { get; set; }
            public double? iss130 { get; set; }
            public double? iss168 { get; set; }
            public double? iss131 { get; set; }
            public double? iss132 { get; set; }
            public double? iss133 { get; set; }
            public double? iss134 { get; set; }
            public double? iss135 { get; set; }
            public double? iss136 { get; set; }
            public double? iss137 { get; set; }
            public double? iss138 { get; set; }
            public double? iss139 { get; set; }
            public double? iss141 { get; set; }
            public double? iss142 { get; set; }
            public double? iss143 { get; set; }
            public double? iss144 { get; set; }
            public double? iss145 { get; set; }
            public double? iss146 { get; set; }
            public double? iss147 { get; set; }
            public double? iss148 { get; set; }
            public double? iss149 { get; set; }
            public double? iss150 { get; set; }
            public double? iss151 { get; set; }
            public double? iss152 { get; set; }
            public double? iss153 { get; set; }
            public double? iss154 { get; set; }
            public double? iss155 { get; set; }
            public double? iss164 { get; set; }
            public double? iss156 { get; set; }
            public double? iss157 { get; set; }
            public double? iss158 { get; set; }
            public double? iss159 { get; set; }
            public double? iss160 { get; set; }
            public double? iss161 { get; set; }
            public double? iss162 { get; set; }
            public double? iss163 { get; set; }
            public double? iss165 { get; set; }
            public double? iss166 { get; set; }
            public double? iss167 { get; set; }
            public double cfa2 { get; set; }
            public double ebit { get; set; }
            public double ebitDa { get; set; }
        }
        public class Yearly
        {
            public string organCode { get; set; }
            public int yearReport { get; set; }
            public int quarterReport { get; set; }
            public double? isb27 { get; set; }
            public double? isb30 { get; set; }
            public double? isb38 { get; set; }
            public double? isb41 { get; set; }
            public double isa20 { get; set; }
            public double isa1 { get; set; }
            public double isa11 { get; set; }
            public double rtq29 { get; set; }
            public double? isb25 { get; set; }
            public double? isb26 { get; set; }
            public double? isb28 { get; set; }
            public double? isb29 { get; set; }
            public double? isb31 { get; set; }
            public double? isb32 { get; set; }
            public double? isb33 { get; set; }
            public double? isb34 { get; set; }
            public double? isb35 { get; set; }
            public double? isb36 { get; set; }
            public double? isb37 { get; set; }
            public double? isb39 { get; set; }
            public double? isb40 { get; set; }
            public double isa16 { get; set; }
            public double isa17 { get; set; }
            public double isa18 { get; set; }
            public double isa19 { get; set; }
            public double isa21 { get; set; }
            public double isa22 { get; set; }
            public double isa23 { get; set; }
            public double isa2 { get; set; }
            public double isa3 { get; set; }
            public double isa4 { get; set; }
            public double isa5 { get; set; }
            public double isa6 { get; set; }
            public double isa7 { get; set; }
            public double isa8 { get; set; }
            public double isa15 { get; set; }
            public double isa9 { get; set; }
            public double isa10 { get; set; }
            public double isa12 { get; set; }
            public double isa13 { get; set; }
            public double isa14 { get; set; }
            public double isa24 { get; set; }
            public double isa102 { get; set; }
            public double? isi103 { get; set; }
            public double? isi104 { get; set; }
            public double? isi51 { get; set; }
            public double? isi52 { get; set; }
            public double? isi53 { get; set; }
            public double? isi54 { get; set; }
            public double? isi55 { get; set; }
            public double? isi56 { get; set; }
            public double? isi57 { get; set; }
            public double? isi105 { get; set; }
            public double? isi58 { get; set; }
            public double? isi59 { get; set; }
            public double? isi106 { get; set; }
            public double? isi60 { get; set; }
            public double? isi61 { get; set; }
            public double? isi62 { get; set; }
            public double? isi63 { get; set; }
            public double? isi64 { get; set; }
            public double? isi65 { get; set; }
            public double? isi66 { get; set; }
            public double? isi67 { get; set; }
            public double? isi68 { get; set; }
            public double? isi69 { get; set; }
            public double? isi70 { get; set; }
            public double? isi176 { get; set; }
            public double? isi175 { get; set; }
            public double? isi107 { get; set; }
            public double? isi71 { get; set; }
            public double? isi108 { get; set; }
            public double? isi109 { get; set; }
            public double? isi110 { get; set; }
            public double? isi73 { get; set; }
            public double? isi111 { get; set; }
            public double? isi72 { get; set; }
            public double? isi74 { get; set; }
            public double? isi75 { get; set; }
            public double? isi76 { get; set; }
            public double? isi77 { get; set; }
            public double? isi78 { get; set; }
            public double? isi79 { get; set; }
            public double? isi80 { get; set; }
            public double? isi81 { get; set; }
            public double? isi82 { get; set; }
            public double? isi83 { get; set; }
            public double? isi84 { get; set; }
            public double? isi85 { get; set; }
            public double? isi86 { get; set; }
            public double? isi87 { get; set; }
            public double? isi90 { get; set; }
            public double? isi88 { get; set; }
            public double? isi89 { get; set; }
            public double? isi177 { get; set; }
            public double? isi178 { get; set; }
            public double? isi179 { get; set; }
            public double? isi180 { get; set; }
            public double? isi100 { get; set; }
            public double? isi93 { get; set; }
            public double? isi91 { get; set; }
            public double? isi92 { get; set; }
            public double? isi97 { get; set; }
            public double? isi112 { get; set; }
            public double? isi113 { get; set; }
            public double? isi114 { get; set; }
            public double? isi94 { get; set; }
            public double? isi95 { get; set; }
            public double? isi96 { get; set; }
            public double? isi98 { get; set; }
            public double? isi99 { get; set; }
            public double? isi101 { get; set; }
            public double? iss115 { get; set; }
            public double? iss116 { get; set; }
            public double? iss117 { get; set; }
            public double? iss118 { get; set; }
            public double? iss119 { get; set; }
            public double? iss120 { get; set; }
            public double? iss121 { get; set; }
            public double? iss122 { get; set; }
            public double? iss42 { get; set; }
            public double? iss44 { get; set; }
            public double? iss45 { get; set; }
            public double? iss46 { get; set; }
            public double? iss48 { get; set; }
            public double? iss47 { get; set; }
            public double? iss43 { get; set; }
            public double? iss49 { get; set; }
            public double? iss123 { get; set; }
            public double? iss50 { get; set; }
            public double? iss124 { get; set; }
            public double? iss125 { get; set; }
            public double? iss126 { get; set; }
            public double? iss127 { get; set; }
            public double? iss128 { get; set; }
            public double? iss129 { get; set; }
            public double? iss130 { get; set; }
            public double? iss168 { get; set; }
            public double? iss131 { get; set; }
            public double? iss132 { get; set; }
            public double? iss133 { get; set; }
            public double? iss134 { get; set; }
            public double? iss135 { get; set; }
            public double? iss136 { get; set; }
            public double? iss137 { get; set; }
            public double? iss138 { get; set; }
            public double? iss139 { get; set; }
            public double? iss141 { get; set; }
            public double? iss142 { get; set; }
            public double? iss143 { get; set; }
            public double? iss144 { get; set; }
            public double? iss145 { get; set; }
            public double? iss146 { get; set; }
            public double? iss147 { get; set; }
            public double? iss148 { get; set; }
            public double? iss149 { get; set; }
            public double? iss150 { get; set; }
            public double? iss151 { get; set; }
            public double? iss152 { get; set; }
            public double? iss153 { get; set; }
            public double? iss154 { get; set; }
            public double? iss155 { get; set; }
            public double? iss164 { get; set; }
            public double? iss156 { get; set; }
            public double? iss157 { get; set; }
            public double? iss158 { get; set; }
            public double? iss159 { get; set; }
            public double? iss160 { get; set; }
            public double? iss161 { get; set; }
            public double? iss162 { get; set; }
            public double? iss163 { get; set; }
            public double? iss165 { get; set; }
            public double? iss166 { get; set; }
            public double? iss167 { get; set; }
            public double cfa2 { get; set; }
            public double ebit { get; set; }
            public double ebitDa { get; set; }
        }
    }
    
}
